name: GitHub Readme Stats Action

on:
  schedule:
    - cron: "0 0 * * *"  # 依需求調整
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: stats-organization/github-readme-stats-action@v1.1.0
        with:
          card: stats          # stats / top-langs / pin / wakatime / gist
          options: ""          # optional
          path: ""             # optional，輸出的 .svg 路徑
          token: ${{ secrets.GH_TOKEN }}
