name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 1 * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch: 
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: waka-box
        uses: matchai/waka-box@v4.0.5
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: f0e660de57cf82942fbd6bb803c6c815
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

